version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "main"
    commit-message:
      prefix: ':green_heart: chore(ci)'

  # Pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "main"
    commit-message:
      prefix: ':green_heart: chore(deps)'
