// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    BoardConsumptionAddWindow: typeof import('./components/BoardConsumptionAddWindow.vue')['default']
    BoardConsumptionDetailsWindow: typeof import('./components/BoardConsumptionDetailsWindow.vue')['default']
    BoardSnackBar: typeof import('./components/BoardSnackBar.vue')['default']
    Canvas: typeof import('./components/Canvas.vue')['default']
    CardPopup: typeof import('./components/CardPopup.vue')['default']
    CardPopupAmountModifier: typeof import('./components/CardPopupAmountModifier.vue')['default']
    CardPopupContent: typeof import('./components/CardPopupContent.vue')['default']
    CardPopupHeader: typeof import('./components/CardPopupHeader.vue')['default']
    CardPopupModificationButtons: typeof import('./components/CardPopupModificationButtons.vue')['default']
    CardPopupSaveButtons: typeof import('./components/CardPopupSaveButtons.vue')['default']
    CardPopupTimeModifier: typeof import('./components/CardPopupTimeModifier.vue')['default']
    EnergyMenu: typeof import('./components/EnergyMenu.vue')['default']
    EnergyMenuAddEnergyWindow: typeof import('./components/EnergyMenuAddEnergyWindow.vue')['default']
    EnergyMenuIcon: typeof import('./components/EnergyMenuIcon.vue')['default']
    EnergyMenuUseEnergyWindow: typeof import('./components/EnergyMenuUseEnergyWindow.vue')['default']
    EquipmentList: typeof import('./components/EquipmentList.vue')['default']
    EquipmentListEquipment: typeof import('./components/EquipmentListEquipment.vue')['default']
    HomeCreateGame: typeof import('./components/HomeCreateGame.vue')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    MarketMenu: typeof import('./components/MarketMenu.vue')['default']
    ProductionList: typeof import('./components/ProductionList.vue')['default']
    ProductionResume: typeof import('./components/ProductionResume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioList: typeof import('./components/ScenarioList.vue')['default']
    ScenarioResume: typeof import('./components/ScenarioResume.vue')['default']
    SetupProductionList: typeof import('./components/SetupProductionList.vue')['default']
    SetupProductionResume: typeof import('./components/SetupProductionResume.vue')['default']
    SetupScenarioList: typeof import('./components/SetupScenarioList.vue')['default']
    SetupScenarioResume: typeof import('./components/SetupScenarioResume.vue')['default']
    SetupValidationSection: typeof import('./components/SetupValidationSection.vue')['default']
    ValidationSetup: typeof import('./components/ValidationSetup.vue')['default']
  }
}
