// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddConsumptionWindow: typeof import('./components/AddConsumptionWindow.vue')['default']
    Equipement: typeof import('./components/Equipement.vue')['default']
    EquipementList: typeof import('./components/EquipementList.vue')['default']
    EquipementType: typeof import('./components/EquipementType.vue')['default']
    Equipments: typeof import('./components/Equipments.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
