// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./components/BaseAlert.vue')['default']
    BaseCanvas: typeof import('./components/BaseCanvas.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    BoardConsumptionAddWindow: typeof import('./components/BoardConsumptionAddWindow.vue')['default']
    BoardConsumptionDetails: typeof import('./components/BoardConsumptionDetails.vue')['default']
    BoardConsumptionDetailsWindow: typeof import('./components/BoardConsumptionDetailsWindow.vue')['default']
    BoardSnackBar: typeof import('./components/BoardSnackBar.vue')['default']
    CardPopup: typeof import('./components/CardPopup.vue')['default']
    CardPopupAmountModifier: typeof import('./components/CardPopupAmountModifier.vue')['default']
    CardPopupContent: typeof import('./components/CardPopupContent.vue')['default']
    CardPopupHeader: typeof import('./components/CardPopupHeader.vue')['default']
    CardPopupModificationButtons: typeof import('./components/CardPopupModificationButtons.vue')['default']
    CardPopupSaveButtons: typeof import('./components/CardPopupSaveButtons.vue')['default']
    CardPopupTimeModifier: typeof import('./components/CardPopupTimeModifier.vue')['default']
    EnergyMenu: typeof import('./components/EnergyMenu.vue')['default']
    EnergyMenuAddEnergyWindow: typeof import('./components/EnergyMenuAddEnergyWindow.vue')['default']
    EnergyMenuIcon: typeof import('./components/EnergyMenuIcon.vue')['default']
    EnergyMenuUseEnergyWindow: typeof import('./components/EnergyMenuUseEnergyWindow.vue')['default']
    EquipmentList: typeof import('./components/EquipmentList.vue')['default']
    EquipmentListEquipment: typeof import('./components/EquipmentListEquipment.vue')['default']
    HomeCreateGame: typeof import('./components/HomeCreateGame.vue')['default']
    MarketMenu: typeof import('./components/MarketMenu.vue')['default']
    MarketMenuIcon: typeof import('./components/MarketMenuIcon.vue')['default']
    MoneyInterface: typeof import('./components/MoneyInterface.vue')['default']
    MoneyMenuIcon: typeof import('./components/MoneyMenuIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupProductionList: typeof import('./components/SetupProductionList.vue')['default']
    SetupProductionResume: typeof import('./components/SetupProductionResume.vue')['default']
    SetupScenarioList: typeof import('./components/SetupScenarioList.vue')['default']
    SetupScenarioResume: typeof import('./components/SetupScenarioResume.vue')['default']
    SetupValidationSection: typeof import('./components/SetupValidationSection.vue')['default']
    TheGameInfoWindow: typeof import('./components/TheGameInfoWindow.vue')['default']
    TheLanguageSelector: typeof import('./components/TheLanguageSelector.vue')['default']
  }
}
