name: Dependencies Reviewer
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Dependencies Review
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: always

  create-issue:
    name: Create an issue in the repository if workflow fails
    needs: [dependency-review]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H 'Content-type: application/json' \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{
            "title":"${{ github.event.pull_request.title }} - Unsecure Dependencies",
            "body":"${{ github.event.pull_request.html_url }}",
            "labels":["dependencies","to sort"]
          }'
