name: Deployment notification
on: [deployment_status] # Triggered for deployment status changes

jobs:
  add-failure-comment:
    name: Add a comment to the commit that caused the failure
    if: github.event.deployment_status.state == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Add commit comment - failure
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H 'Content-type: application/json' \
          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
          --data '{"body": "Deployment of the app to Vercel has failed."}'
