name: Deployment workflow

on:
  push:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  Preview:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preview
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}


  Production:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      cmd_flag: --prod
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
