name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:

      - name: Create deployment in GitHub
        # Create a deployment in GitHub so that the status can be updated later, and store the deployment ID in an environment variable
        id: create_deployment
        run: |
          curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "'X-GitHub-Api-Version: 2022-11-28" \
          -H 'Content-type: application/json' \
          https://api.github.com/repos/${{ github.repository }}/deployments \
          -d '{
            "ref":"${{ github.event.ref }}",
            "payload":"{}",
            "environment":"preview",
            "description":"Preview deployment for ${{ github.event.head_commit.message }}",
          }'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Vercel CLI
        run: pnpm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }} | tee output.log

      - name: Build Project Artifacts
        run: |
          vercel build --yes --token=${{ secrets.VERCEL_TOKEN }} | tee output.log

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} | tee output.log

      - name: Update deployment status to success in GitHub
        if: ${{ success() }}
        run: |
          curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -H 'Content-type: application/json' \
          https://api.github.com/repos/${{ github.repository }}/deployments/${{ fromJson(steps.create_deployment.outputs.result).id }}/statuses \
          -d '{
            "environment":"preview",
            "state":"success",
            "log_url":"'"grep -oP 'Inspect: \Khttps://\S+' output.log"'",
            "environment_url":"'"grep -oP 'Preview: \Khttps://\S+' output.log"'",
            "description":"Deployment finished successfully."
          }'

      - name: Update deployment status to failure in GitHub
        if: ${{ failure() }}
        run: |
          curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -H 'Content-type: application/json' \
          https://api.github.com/repos/${{ github.repository }}/deployments/${{ fromJson(steps.create_deployment.outputs.result).id }}/statuses \
          -d '{
            "environment":"preview",
            "state":"failure",
            "log_url":"'"grep -oP 'Inspect: \Khttps://\S+' output.log"'",
            "environment_url":"'"grep -oP 'Preview: \Khttps://\S+' output.log"'",
            "description":"Deployment failed."
          }'

      - name: Create issue
        if: ${{ failure() }}
        run: |
          curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -H 'Content-type: application/json' \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{
            "title":"Failed to deploy preview for ${{ github.event.head_commit.message }}",
            "body":" '"cat output.log"' ",
            "labels":["bug","to sort"]
          }'

      - name: Create comment if pull-request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          curl -L \
          -X PATCH \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "'X-GitHub-Api-Version: 2022-11-28" \
          -H 'Content-type: application/json' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
          -d '{
            "body": "| Name | Status | Preview |\n| :--- | :----- | :------ |\n| **ebalanceplusgame** | :white_check_mark: Ready ([Inspect]('"grep -oP 'Inspect: \Khttps://\S+' output.log"')) | [Visit Preview]('"grep -oP 'Preview: \Khttps://\S+' output.log"') |"
          }'
